#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

get_unique_dir() {
    local base="$1"
    local candidate="$base"
    local i=1
    while [ -e "$candidate" ]; do
        candidate="${base}_$i"
        i=$((i + 1))
    done
    printf '%s' "$candidate"
}

run_baseline() {
    local CONFIG="$1"
    local DATASET="$2"

    echo "=== Running DARTS baseline for $DATASET ==="
    python DARTS_baseline.py --hyperparameters_json "$CONFIG"

    local BASE="best_models_${DATASET}_baseline"
    local UNIQUE_DIR
    UNIQUE_DIR="$(get_unique_dir "$BASE")"

    if [ -d "best_models" ]; then
        mv best_models "$UNIQUE_DIR"
        echo "[OK] Saved to $UNIQUE_DIR"
    else
        echo "[WARN] No 'best_models' directory generated by the run."
    fi
}

# Запуск для FashionMNIST
# первая переменная -- конфиг, вторая -- префикс директории
run_baseline "surrogate_hp_fashionmnist.json" "fashionmnist"
