name: base
dependencies:
- conda-forge::cudatoolkit=11.3.1
- numpy=1.21.2
- pillow=8.4.0
- pip=21.2.4
- python=3.9.7
- pytorch::pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
- scipy=1.12.0
- pytorch::torchvision=0.11.3=py39_cu113
- ffmpeg=4.2.2
- tqdm=4.62.3
- ipython=8.18.1
- pip:
  - torch-geometric==2.6.1
  - nni==3.0
  - scikit-learn==1.6.1
  - pytorch-lightning==2.4.0
  - torchmetrics==1.6.0
  - graphviz==0.21
  - matplotlib==3.9.4